version: '3.8'

services:
  portfolio:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
